export { default as Navbar } from './Navbar/Navbar'
export { default as HomeBanner } from './HomeBanner/HomeBanner'
export { default as Comment } from './Comment/Comment'
export { default as StarRating } from './StarRating/StarRating'
export { default as Specialties } from './Specialties/Specialties'
export { default as PopularProducts } from './PopularProducts/PopularProducts'
export { default as Writer } from './Writer/Writer'
